on:
  push:
    branches:
    - main
jobs:
  BuildBin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2.1
        target: esp32s3
        path: '.'
        command: idf.py build
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: |
          build/MorningClock.bin
          build/version.txt
          
  UploadOSS:
    runs-on: ubuntu-latest
    needs: BuildBin
    environment: AliyunOSS

    steps:
    - name: Download OSSutil
      run: wget ${{ vars.OSSUTIL_DOWNLOADURL }} -O ossutil
    - run: chmod +x ossutil
    - name: Set ossutilconfig
      run: echo "${{ secrets.OSSUTILCONFIG }}" > ossutilconfig
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - run: echo "::notice Version `cat artifact/version.txt` will upload"
    - run: ./ossutil cp ./artifact/MorningClock.bin oss://MorningClock/MorningClock.bin -f -c ossutilconfig
    - run: ./ossutil cp ./artifact/MorningClock.bin oss://MorningClock/MorningClock.`cat artifact/version.txt`.bin -f -c ossutilconfig
    - run: echo "::notice Version `cat artifact/version.txt` uploaded"
