on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0
        target: esp32
        path: '.'
        command: idf.py build
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MorningRing.bin
        path: build/MorningRing.bin
